### ISSUE TITLE
There is a bug: the solutions vector is not be cleared at the begin of the repeated matching procedures, which leads to solutions are repeatedly stored.

### ISSUE THREAD

**Issue by RongqinChen** [MiviaLab/vf3lib#11]
Dear Vincenzo,

Thanks for your great work.

I found a bug. The solutions vector in the repeated matching procedures, as show below, should be cleared at the first,  otherwise repeated solutions are saved.

```
#ifndef TRACE
do
{
	rep++;
	me->ResetSolutionCounter();

	gettimeofday(&iter, NULL);
#endif
	if(check.CheckSubgraphIsomorphism())
	{
		VF3NodeSorter<data_t, Empty, SubIsoNodeProbability<data_t, Empty> > sorter(&targ_graph);
		std::vector<nodeID_t> sorted = sorter.SortNodes(&patt_graph);

		#ifdef TRACE
		me->InitTrace(outfilename);
		#endif

		state_t s0(&patt_graph, &targ_graph, class_patt.data(), class_targ.data(), classes_count, sorted.data());
		me->FindAllMatchings(s0);

		#ifdef TRACE
		me->FlushTrace();
		#endif

	}

#ifndef TRACE
	gettimeofday(&end,NULL);

	totalExecTime += GetElapsedTime(iter, end);
	end = me->GetFirstSolutionTime();
	timeFirst += GetElapsedTime(iter, end);
} while (totalExecTime < opt.repetitionTimeLimit);
timeAll = totalExecTime/rep;
timeFirst /= rep;
```

And I insert a line into the `ResetSolutionCounter` function to fix this bug, as shown below
```cpp
virtual void ResetSolutionCounter()
{
	solCount = 0;
	solutions.clear();
}
```

Best wishes.

**Comment by Issac-Newton** [comment]
encounter the same problem
Good solution


> Dear Vincenzo,
> 
> Thanks for your great work.
> 
> I found a bug. The solutions vector in the repeated matching procedures, as show below, should be cleared at the first, otherwise repeated solutions are saved.
> 
> ```
> #ifndef TRACE
> do
> {
> 	rep++;
> 	me->ResetSolutionCounter();
> 
> 	gettimeofday(&iter, NULL);
> #endif
> 	if(check.CheckSubgraphIsomorphism())
> 	{
> 		VF3NodeSorter<data_t, Empty, SubIsoNodeProbability<data_t, Empty> > sorter(&targ_graph);
> 		std::vector<nodeID_t> sorted = sorter.SortNodes(&patt_graph);
> 
> 		#ifdef TRACE
> 		me->InitTrace(outfilename);
> 		#endif
> 
> 		state_t s0(&patt_graph, &targ_graph, class_patt.data(), class_targ.data(), classes_count, sorted.data());
> 		me->FindAllMatchings(s0);
> 
> 		#ifdef TRACE
> 		me->FlushTrace();
> 		#endif
> 
> 	}
> 
> #ifndef TRACE
> 	gettimeofday(&end,NULL);
> 
> 	totalExecTime += GetElapsedTime(iter, end);
> 	end = me->GetFirstSolutionTime();
> 	timeFirst += GetElapsedTime(iter, end);
> } while (totalExecTime < opt.repetitionTimeLimit);
> timeAll = totalExecTime/rep;
> timeFirst /= rep;
> ```
> 
> And I insert a line into the `ResetSolutionCounter` function to fix this bug, as shown below
> 
> ```c++
> virtual void ResetSolutionCounter()
> {
> 	solCount = 0;
> 	solutions.clear();
> }
> ```
> 
> Best wishes.

Encounter the same problem
Good Solution

**Comment by vincarlet** [comment]
Fixed, thanks!
