### ISSUE TITLE
Some questions about vf3 algorithm

### ISSUE THREAD

**Issue by yinkaaiwu** [MiviaLab/vf3lib#16]
I recently downloaded this program from https://github.com/MiviaLab/vf3lib and compiled Makefile successfully on M1pro MacOS.

When I try to solve subgraph isomorphism on G1 and G2, program didn’t find any solutions. But clearly there is at least one solution(0,0: 1,1: 2,2: 3,3: 4,4:).

![image](https://user-images.githubusercontent.com/100132369/215238399-da7dfc55-739b-4826-9219-113ab10a45c3.png)
![image](https://user-images.githubusercontent.com/100132369/215238414-e7021633-6ff9-418c-b265-f7164e4bfc17.png)

I'm not sure why this is happening. Input files are already in the attachment. Please point out my mistakes, thanks!
Looking forward to your reply.

G1 inputfile
7
0 1
1 3
2 1
3 2
4 2
5 1
6 1
1
0 3
2
1 3
1 4
1
2 4
4
3 0
3 1
3 4
3 5
4
4 1
4 2
4 3
4 6
1
5 3
1
6 4

G2 inputfile
5
0 1
1 3
2 1
3 2
4 2
1
0 3
2
1 3 
1 4
1
2 4
2
3 0
3 1
2
4 1
4 2

**Comment by dmyyy** [comment]
You're trying to find a non-induced subgraph isomorphism (this library seems to focus on supporting induced subgraph matching)

**Comment by yinkaaiwu** [comment]
> You're trying to find a non-induced subgraph isomorphism (this library seems to focus on supporting induced subgraph matching)

Ohhhh, I see! Thanks you very much!

**Comment by Me-Doc** [comment]
The readme says this lib can solve the Non-induced subgraph isomorphism, but do you know how should I do to use it? Thanks!
