### ISSUE TITLE
Problems building Makefile

### ISSUE THREAD

**Issue by Aidonnou** [MiviaLab/vf3lib#3]
I am using a Windows 10 64 bits and I am having problems building the Makefile.

The error I find are related with the sig_handler function. 

I managed to built vf3 by commenting the lines 29 to 53 and from 87 to 93.

Besides, hardcoding/commenting the code, what am I doing wrong?

cheers

**Comment by vincarlet** [comment]
sig_handler are for the linux version, you can remove it from the main if you are working on windows.
Try to complile using by adding -DWIN32 to avoid compiling unsupported windows code.
