### ISSUE TITLE
Bugs with your code

### ISSUE THREAD

**Issue by shaofengzeng** [MiviaLab/vf3lib#6]
I think there is something wrong with your code.
For exmaple, I have modified the `Makefile` and tried the following two commands,
CFLAGS= -std=c++11 -march=native -O3 -Wno-deprecated
and
CFLAGS= -std=c++11 -march=native -O0 -Wno-deprecated
I got 8 and 13 solutions respectively.

**Comment by shaofengzeng** [comment]
Maybe we should delete the private variable 'induced' of VF3SubState

**Comment by vincarlet** [comment]
Fixed in the latest version
