### ISSUE TITLE
vf3 and vf3p produce different results

### ISSUE THREAD

**Issue by xianglizhi123** [MiviaLab/vf3lib#7]
Hello 
I tested vf3 and vf3p, but they are producing different results.
For example:
./bin/vf3 ./test/bvg1.sub.grf ./test/bvg1.grf
13 1.71755e-06 6.34102e-06
./bin/vf3p ./test/bvg1.sub.grf ./test/bvg1.grf -a 2 -t 8
8 0.000162754 0.000242756

**Comment by vincarlet** [comment]
Fixed in the latest version (see issue 5)
